### ISSUE TITLE
SQL Tables

### ISSUE THREAD

**Issue by raghavgarg1257** [ashishks55/Raspberry-Pi-Smart-Class#1]
could you please upload the sql format of the tables, you have designed.

**Comment by professor-proton** [comment]
ashish please upload the format of the sql tables used. after alot of tries it keeps on returning the table errors

**Comment by ashishks55** [comment]
Here is the .sql file you can simply import this in phpmyadmin.
https://github.com/ashishks55/Raspberry-Pi-Smart-Class/blob/master/RP3.sql
